# Generated by Django 6.1.1 on 2026-10-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turma_idade_para_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turma',
            new_name='TurmaCatequeseInfantil',
        ),
    ]
